#!/usr/bin/env python3

# describe2: query the wikipedia database from the commandline
# AO-2021
#
# INSTALL : pip install wikipedia
#           pip install termcolor
#           cp describe ~/bin (or a location in your $PATH)
#           chmod u+x describe
#
import wikipedia
import sys
import os
import pycurl, requests
from termcolor import colored

def main():
    argc = len(sys.argv)
    if argc == 1:
        print("describe \"Some Name\" <WIKILANGUAGECODES> --all --exact")
        return
    langcodes = sys.argv[2:argc]
    al = 0
    exact = 0
    if "--all" in langcodes:
        n = langcodes.index('--all')
        al = 1
        langcodes.pop(n)
    if "--exact" in langcodes:
        n = langcodes.index('--exact')
        exact = 1
        langcodes.pop(n)
    if len(langcodes) == 0:
        langcodes=['en']
    for langc in langcodes:
        try:
            wikipedia.set_lang(langc)
            if exact == 0:
                page = wikipedia.search(sys.argv[1])
                page2 = wikipedia.page(page[0])
            else:
                page = wikipedia.search(sys.argv[1])
                page2 = wikipedia.page(sys.argv[1], auto_suggest=False)
                 
            print (colored(langc+":", 'green'))
            b = bytearray(page2.title, 'utf-8')
            title = b.decode('utf-8')
            print (colored(title,'red', attrs=['bold']))
            if al: 
                print (page2.content)
            else:
                print (page2.summary)
            #print (page2.links)
            print (colored(page2.url, 'blue'))
            print ('--')
        except wikipedia.exceptions.DisambiguationError as e:
            print(e)
        except wikipedia.exceptions.PageError as e:
            print(e)
        except requests.exceptions.ConnectionError:
            print (langc+": Not found\n")

				
if __name__ == "__main__":
    main()
	
